# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-Feedback
version:      1.05
version_from: lib/CGI/Application/Plugin/Feedback.pm
installdirs:  site
requires:
    CGI::Application:              0
    CGI::Application::Plugin::Session: 0
    CGI::Session:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
